#!/usr/bin/env ts-node

import { generatorHandler, GeneratorOptions } from '@prisma/generator-helper';
import { promises as fs } from 'fs';
import path from 'path';
import { DMMF } from '@prisma/generator-helper';

generatorHandler({
  onManifest() {
    return {
      defaultOutput: '../src',
      prettyName: 'DTO Generator',
      requiresGenerators: ['prisma-client-js'],
    };
  },
  async onGenerate(options: GeneratorOptions) {
    const models = options.dmmf.datamodel.models as any;
    const outputDir = options.generator.output?.value;
    
    if (!outputDir) {
      throw new Error('No output directory specified');
    }

    // Generowanie wszystkich DTOs
    const dtoContent = generateAllDTOs(models);

    // Zapisanie do pliku
    const outputPath = path.resolve(outputDir, 'generated-dtos.ts');
    
    // Upewnij się, że folder istnieje
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, dtoContent, 'utf-8');

    console.log(`✅ Generated DTOs at ${outputPath}`);
  },
});

function generateAllDTOs(models: DMMF.Model[]): string {
  const lines: string[] = [];

  // Header
  lines.push('/**');
  lines.push(' * Auto-generated DTOs from Prisma schema');
  lines.push(' * DO NOT EDIT MANUALLY - This file is generated by prisma-generator');
  lines.push(' */');
  lines.push('');
  lines.push("import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';");
  lines.push('');

  for (const model of models) {
    // Generate Create DTO
    lines.push(...generateCreateDTO(model));
    lines.push('');

    // Generate Update DTO
    lines.push(...generateUpdateDTO(model));
    lines.push('');

    // Generate Response DTO
    lines.push(...generateResponseDTO(model));
    lines.push('');
  }

  return lines.join('\n');
}

function generateCreateDTO(model: DMMF.Model): string[] {
  const lines: string[] = [];
  const className = `Create${model.name}Dto`;

  lines.push(`// ========== ${model.name} Create DTO ==========`);
  lines.push(`export class ${className} {`);

  for (const field of model.fields) {
    // Pomijamy: id (auto-generated), relacje, timestamps auto-generated
    if (
      field.name === 'id' ||
      field.kind === 'object' ||
      field.hasDefaultValue ||
      field.isUpdatedAt
    ) {
      continue;
    }

    const tsType = mapPrismaTypeToTS(field.type);
    const isOptional = !field.isRequired;
    const decorator = isOptional ? '@ApiPropertyOptional' : '@ApiProperty';

    lines.push(`  ${decorator}({`);
    lines.push(`    description: '${field.name}',`);
    if (field.type === 'String') {
      lines.push(`    type: String,`);
    } else if (field.type === 'Int' || field.type === 'Float') {
      lines.push(`    type: Number,`);
    } else if (field.type === 'Boolean') {
      lines.push(`    type: Boolean,`);
    } else if (field.type === 'DateTime') {
      lines.push(`    type: Date,`);
    }
    lines.push(`  })`);
    lines.push(`  ${field.name}${isOptional ? '?' : ''}: ${tsType};`);
    lines.push('');
  }

  lines.push('}');

  return lines;
}

function generateUpdateDTO(model: DMMF.Model): string[] {
  const lines: string[] = [];
  const className = `Update${model.name}Dto`;

  lines.push(`// ========== ${model.name} Update DTO ==========`);
  lines.push(`export class ${className} {`);

  for (const field of model.fields) {
    // Pomijamy: id, relacje, timestamps auto-generated (createdAt)
    if (
      field.name === 'id' ||
      field.kind === 'object' ||
      (field.hasDefaultValue && !field.isUpdatedAt)
    ) {
      continue;
    }

    const tsType = mapPrismaTypeToTS(field.type);

    lines.push(`  @ApiPropertyOptional({`);
    lines.push(`    description: '${field.name}',`);
    if (field.type === 'String') {
      lines.push(`    type: String,`);
    } else if (field.type === 'Int' || field.type === 'Float') {
      lines.push(`    type: Number,`);
    } else if (field.type === 'Boolean') {
      lines.push(`    type: Boolean,`);
    } else if (field.type === 'DateTime') {
      lines.push(`    type: Date,`);
    }
    lines.push(`  })`);
    lines.push(`  ${field.name}?: ${tsType};`);
    lines.push('');
  }

  lines.push('}');

  return lines;
}

function generateResponseDTO(model: DMMF.Model): string[] {
  const lines: string[] = [];
  const className = `${model.name}ResponseDto`;

  lines.push(`// ========== ${model.name} Response DTO ==========`);
  lines.push(`export class ${className} {`);

  for (const field of model.fields) {
    // Pomijamy tylko relacje (możemy pokazać foreign keys)
    if (field.kind === 'object') {
      continue;
    }

    const tsType = mapPrismaTypeToTS(field.type);
    const isOptional = !field.isRequired;
    const decorator = isOptional ? '@ApiPropertyOptional' : '@ApiProperty';

    lines.push(`  ${decorator}({`);
    lines.push(`    description: '${field.name}',`);
    if (field.type === 'String') {
      lines.push(`    type: String,`);
    } else if (field.type === 'Int' || field.type === 'Float') {
      lines.push(`    type: Number,`);
    } else if (field.type === 'Boolean') {
      lines.push(`    type: Boolean,`);
    } else if (field.type === 'DateTime') {
      lines.push(`    type: Date,`);
    }
    lines.push(`  })`);
    lines.push(`  ${field.name}${isOptional ? '?' : ''}: ${tsType};`);
    lines.push('');
  }

  lines.push('}');

  return lines;
}

function mapPrismaTypeToTS(prismaType: string): string {
  const typeMap: Record<string, string> = {
    String: 'string',
    Int: 'number',
    Float: 'number',
    Boolean: 'boolean',
    DateTime: 'Date',
    Json: 'any',
    Bytes: 'Buffer',
  };

  return typeMap[prismaType] || 'any';
}

