/**
 * Auto-generated DTOs from Prisma schema
 * DO NOT EDIT MANUALLY - This file is generated by prisma-generator
 */

import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// ========== User Create DTO ==========
export class CreateUserDto {
  @ApiProperty({
    description: 'email',
    type: String,
  })
  email: string;

  @ApiProperty({
    description: 'passwordHash',
    type: String,
  })
  passwordHash: string;
}

// ========== User Update DTO ==========
export class UpdateUserDto {
  @ApiPropertyOptional({
    description: 'email',
    type: String,
  })
  email?: string;

  @ApiPropertyOptional({
    description: 'passwordHash',
    type: String,
  })
  passwordHash?: string;
}

// ========== User Response DTO ==========
export class UserResponseDto {
  @ApiProperty({
    description: 'id',
    type: String,
  })
  id: string;

  @ApiProperty({
    description: 'email',
    type: String,
  })
  email: string;

  @ApiProperty({
    description: 'passwordHash',
    type: String,
  })
  passwordHash: string;

  @ApiProperty({
    description: 'createdAt',
    type: Date,
  })
  createdAt: Date;
}

// ========== Cv Create DTO ==========
export class CreateCvDto {
  @ApiProperty({
    description: 'userId',
    type: String,
  })
  userId: string;

  @ApiProperty({
    description: 's3Key',
    type: String,
  })
  s3Key: string;

  @ApiProperty({
    description: 'filename',
    type: String,
  })
  filename: string;
}

// ========== Cv Update DTO ==========
export class UpdateCvDto {
  @ApiPropertyOptional({
    description: 'userId',
    type: String,
  })
  userId?: string;

  @ApiPropertyOptional({
    description: 's3Key',
    type: String,
  })
  s3Key?: string;

  @ApiPropertyOptional({
    description: 'filename',
    type: String,
  })
  filename?: string;
}

// ========== Cv Response DTO ==========
export class CvResponseDto {
  @ApiProperty({
    description: 'id',
    type: String,
  })
  id: string;

  @ApiProperty({
    description: 'userId',
    type: String,
  })
  userId: string;

  @ApiProperty({
    description: 's3Key',
    type: String,
  })
  s3Key: string;

  @ApiProperty({
    description: 'filename',
    type: String,
  })
  filename: string;

  @ApiProperty({
    description: 'createdAt',
    type: Date,
  })
  createdAt: Date;
}

// ========== Letter Create DTO ==========
export class CreateLetterDto {
  @ApiProperty({
    description: 'userId',
    type: String,
  })
  userId: string;

  @ApiProperty({
    description: 'html',
    type: String,
  })
  html: string;

  @ApiPropertyOptional({
    description: 'pdfS3Key',
    type: String,
  })
  pdfS3Key?: string;
}

// ========== Letter Update DTO ==========
export class UpdateLetterDto {
  @ApiPropertyOptional({
    description: 'userId',
    type: String,
  })
  userId?: string;

  @ApiPropertyOptional({
    description: 'html',
    type: String,
  })
  html?: string;

  @ApiPropertyOptional({
    description: 'pdfS3Key',
    type: String,
  })
  pdfS3Key?: string;

  @ApiPropertyOptional({
    description: 'updatedAt',
    type: Date,
  })
  updatedAt?: Date;
}

// ========== Letter Response DTO ==========
export class LetterResponseDto {
  @ApiProperty({
    description: 'id',
    type: String,
  })
  id: string;

  @ApiProperty({
    description: 'userId',
    type: String,
  })
  userId: string;

  @ApiProperty({
    description: 'html',
    type: String,
  })
  html: string;

  @ApiPropertyOptional({
    description: 'pdfS3Key',
    type: String,
  })
  pdfS3Key?: string;

  @ApiProperty({
    description: 'createdAt',
    type: Date,
  })
  createdAt: Date;

  @ApiProperty({
    description: 'updatedAt',
    type: Date,
  })
  updatedAt: Date;
}
